### ISSUE TITLE
Course searchbox still displays in the Frontpage Textbox

### ISSUE THREAD

**Issue by buergermeister75** [kennibc/moodle-theme_pioneer#10]
Hi.  I've installed v1.2.7 and the course search box and icons still display in the Frontpage Textbox (theme_pioneer | fptextbox) despite not having any text in there and Show Icon Nav and Searchbox (theme_pioneer | fptextboxiconnav) being unchecked.  I've also checked the HTML setting of fptextbox to verify that there is no residual tags in there that could be interpreted as text.  Any help would be appreciated as I'd like to hid this from displaying on the front page for our Moodle v3 site.

Thank you - Bruce

**Comment by kennibc** [comment]
i see theissue fully now.  will have fix soon.

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
*Michigan Moodle User group
<https://www.facebook.com/groups/819830188053375/> (Facebook)*
http://iblog.dearbornschools.org/technology
http://webmaster.dearbornschools.org

**Comment by buergermeister75** [comment]
Awesome.  Thank you!

**Comment by kennibc** [comment]
Fixed in 1.2.8.  It will be up on moodle.org this week.  Otherwise you can grab the copy from github.
