### ISSUE TITLE
Which version is git actually getting?

### ISSUE THREAD

**Issue by markpea** [kennibc/moodle-theme_pioneer#13]
I have just installed the Pioneer theme into a Moodle 3.1 install using git  

`git clone https://github.com/kennibc/moodle-theme_pioneer pioneer`

The version.php indicates 

`$plugin->release = 'Pioneer v1.4.2';`
`$plugin->version   = 2016053100;`
`$plugin->requires  = 2014050800;`
`$plugin->component = 'theme_pioneer';`

But Plugins overview within Moodle indicates

There is a new version 2016060700 available!
Release Pioneer v1.4.3.1 for Moodle v3.1

What gives? `git branch -a` indicates I'm on the master branch and a `git pull` says 'Already up to date'. How do I get v1.4.3.1 ?

**Comment by kennibc** [comment]
Please download from Moodle to install.  I am not very experienced with
Github It may not contain the most recent version.

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
*Michigan Moodle User group
<https://www.facebook.com/groups/819830188053375/> (Facebook)*
*Michigan Moodle User Group
<https://plus.google.com/u/0/communities/113077058997214337239> (Google +)*
http://iblog.dearbornschools.org/technology
http://webmaster.dearbornschools.org

**Comment by markpea** [comment]
Downloading and installing from Moodle makes it a real pain to keep the module updated.
