### ISSUE TITLE
Add own @copyright tags

### ISSUE THREAD

**Issue by mudrd8mz** [kennibc/moodle-theme_pioneer#3]
Leaving the original @copyright tags in the files without adding your own name and year may suggest that the theme was developed by the original authors. The recommended model is:

* For files specific to your theme (such as version.php), put just yourself into @copyright tags. It is then clear who is to be blamed for the bugs in it (instead of Frédéric, Gareth, Julian and others).
* In the files that are mostly copied over from another existing theme, leave original @copyright tags with the original years, and add your own. Ideally with a note that the file was based on some others' work.

**Comment by mudrd8mz** [comment]
See for example how it was done in jquery/plugins.php

Additionally, you should fix _all_ @package keywords and put the name of your theme there.

**Comment by kennibc** [comment]
In the latest 1.1fix commit I changed the tags.
