### ISSUE TITLE
Hard-coded English language strings in Pioneer theme

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kennibc/moodle-theme_pioneer#5]
Hi,
I just translated your Pioneer Moodle theme into mexican spanish in AMOS.
But when I use this translated  theme in a local sever, I found that there are some hard-wired English language strings in the theme:

When I (at http://localhost/my/) hover over the icons for home, calendar, badges and courses, the names that appear are exactly "My Home", "Calendar", "Badges" and "Courses"..

I think that your (already great) Pioneer theme for Moodle would be even better if you changed these hard-wired English strings into variables, that would be available for translation in AMOS.

The "Welcome to Moodle" text and the message "This is the Pioneer theme brought to you by Dearborn..." are also hard-coded.

When at http://localhost/my/ , the "Find" button is hard-coded..

Thanks in advance for your help.

**Comment by germanvaleroelizondo** [comment]
Hi,
The "Welcome to Moodle" text and the message "This is the Pioneer theme brought to you by Dearborn..." are also hard-coded.

**Comment by germanvaleroelizondo** [comment]
Hi, I just closed the issue by mistake :(

**Comment by kennibc** [comment]
The top icons tooltips are defaults set in settings.php just like default colors.  They are there to help people get started.  Is there a way to pull the language string into defaults?  I will play with this tomorrow and try to get a fix.  Please let me know any suggestions or other language issues you find.  Thank you.

**Comment by germanvaleroelizondo** [comment]
Thanks Chris, 
I will try this theme at home later and get back to you if I find any more hard-coded Language strings.

**Comment by kennibc** [comment]
Hello @germanvaleroelizondo ,
I fixed a few of the language strings.  I added in the top navigation search items.  I also found 2 language strings that were missing.  

I am having an issue with the top navigation icons (My Home, Calendar, Badges, Courses) as these are just suggested defaults in settings.php.  I am unsure how I can import a language string into the theme settings page for these 4 items.  If you have any suggestions let me know.  

I could leave those 4 items blank, but I think they are needed to show people how to add an icon link.
What do you think?

**Comment by germanvaleroelizondo** [comment]
Hi Chris,

Thanks for the very fast, efficient, friendly fixes.
I am not a programer, merely a veterinarian. Perhaps David Mudrak knows the way to accomplish this. He has been extremely helpful and accomplished at improving Moodle languages. Perhaps he can contact the maintainer for settings.php (core HQ?) to upgrade the code.

**Comment by kennibc** [comment]
Settings.php is in the theme.  I set a default parameter for those 4 icons as a demonstration to give users an idea of how to setup and use the icon navigation.  At any point the site admin can change that text from the administration of the theme.  I

t is only hard-coded as a default setting but the user can translate it on their own in the admin panel inside the theme settings.  Is this acceptable?

**Comment by germanvaleroelizondo** [comment]
Let me give it a try (6 hours to get home and try it) and I will report back to you. Thanks.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,
A minor typo in coursegradeinfodesc | theme_pioneer "Checking this box will display the coruse ..." should be "course".

**Comment by kennibc** [comment]
Pushed to github.  
Will release on moodle.org when I publish the 1.1.9 version.  
Thank you very much for helping in translating this theme.

**Comment by germanvaleroelizondo** [comment]
I am having a bad AMOS day. I Will get back as soon as I boot Linux.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,
I tested your theme again and I just added a few pages in the Moodle Docs that show up when you click on the 'Moodle Docs for this page' links at the bottom of several configuration pages for your theme.

Please look at https://docs.moodle.org/30/en/admin/setting/theme_pioneer_iconnav and change as needed.

Thanks again for another great (easily translatable too) Moodle theme :)

**Comment by germanvaleroelizondo** [comment]
![pioneer translated icons names](https://cloud.githubusercontent.com/assets/2671923/11276568/32c96896-8ea8-11e5-8b89-8953bd62cb8e.png)

**Comment by germanvaleroelizondo** [comment]
Acceptable it is. 
Great programmer You are.
Non-English (Mexican Spanish) Yoda Moodler congratulates You :)
Thanks again.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,
Would you think it would be easier to understand if you changed naviconbuttontextdesc | theme_pioneer , 

which currently is "Text to appear in the tooltip of the icon."

to "Text to appear in the tooltip of the icon when the mouse hovers over it." ?

**Comment by kennibc** [comment]
I will take a look at the help pages.  I also changed your description in naviconbuttontextdesc | theme_pioneer.

There are some new items coming in the 1.1.9 version about to be uploaded.  I added a few items.  I promise it will slow down once things are stable.  We are getting some good feedback and I am making changes to the theme based on the feedback where it makes sense.

**Comment by kennibc** [comment]
I pushed out the 1.1.9 version.  It added a new feature or two.  It also has some of your suggestions.

**Comment by germanvaleroelizondo** [comment]
Hi Chris,
I am trying the new version. So far, it looks very good. Congratulations.

The new string sectionheadericondesc | theme_pioneer:

This icon appears before the title of every topic for weekly and topic based course formats. Use the unicode setting from Font Awesome. List is <a href="http://fortawesome.github.io/Font-Awesome/cheatsheet/" target="_new">here</a>

perhaps could also include some additional info such as ". The f02d (default) icon is a book."

Thanks again for this very nice theme.

BTW: I noticed that the SocialWall Course format is not listed as Moodle 3.0 compatible yet in the Moodle plugins database .

**Comment by kennibc** [comment]
I haven't had a chance to officially check out Socialwall on M3.0.  I think it will work though.  We are only updating our install to Moodle 2.9 next monday.  We are generally current -1.

**Comment by germanvaleroelizondo** [comment]
My University server is currently 2.6. The local IT guy promised an upgrade over 1 year ago :( 

I checked it in a local 3.0 server OK.

SocialWall plugin has been downloaded by over 2000 users, and , as it was recently awarded the Reviewer's choice award, I'd think it will be checked in many many (Moodle 3.0) servers. 
Congratulations.

I also added Moodle Docs page linked by 'Moodle Docs for this page' at https://docs.moodle.org/30/en/admin/setting/theme_pioneer_generic .

Please feel free to add or change as needed.

**Comment by kennibc** [comment]
Excellent.  Thank you for your hard work in translating this so that others can enjoy these plugins and understand the various features.
