### ISSUE TITLE
Tiles for Courses overlap

### ISSUE THREAD

**Issue by derekc** [kennibc/moodle-theme_pioneer#6]
Using the default icons for courses, they don't tile sometimes:

![image](https://cloud.githubusercontent.com/assets/687780/11401806/3a701d6e-93f9-11e5-8635-d947a3dd29c4.png)

Pioneer Version 2015112600

**Comment by kennibc** [comment]
I will get a fix out next week but the answer is on here:
https://github.com/kennibc/moodle-theme_pioneer/blob/master/renderers/course_renderer.php#L103
Change the width to 100% and that will fix the overlap issue.
