### ISSUE TITLE
Minor typo in one English language string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kennibc/moodle-theme_pioneer#7]
Hi Chris,
I was translating the new strings for the new version of this plugin when I noticed a small typo in tabinfodesc | theme_pioneer:

"Add a title and a desctription below. This will only appear on the frontpage as a slider. The button to activate the slider is located in the top header."

"desctription" should be "description".

Thanks again for an ever-improving great Moodle theme.

**Comment by kennibc** [comment]
Thanks.  Will fix for next release.  I was so happy to get the new tabs feature working I didn't check spelling!

**Comment by kennibc** [comment]
fixed in 1.2.2

**Comment by germanvaleroelizondo** [comment]
Thanks
