### ISSUE TITLE
Log out when selecting icons in header

### ISSUE THREAD

**Issue by jamiebillingham** [kennibc/moodle-theme_pioneer#8]
We have just upgraded our Moodle site on our test server - local server - to Moodle 3.0 Build 20151126 and are in the process of testing the Pioneer theme.

When I log in as an admin or as a student and then select any of the the My home, calendar, badges or All courses icons I am logged out. The rest of the links seem to be working though i.e. the My Courses menu items.

![image](https://cloud.githubusercontent.com/assets/13277695/11543374/12e73d5c-98f1-11e5-918e-e6709796dd4e.png)

**Comment by kennibc** [comment]
Those links are set in the theme settings.  The links can take you anywhere.  While the theme tries to add 4 examples, not every server is the same. For instance you might need to add /moodle/ to each of those links to work on your test server.  This is done in Appearance > Themes > Pioneer > Icon Navigation.  ![icon navigation](https://cloud.githubusercontent.com/assets/1692748/11543872/f75c91f6-990c-11e5-9b82-3ecaf5e92885.png)

**Comment by kennibc** [comment]
The reason you would need to add /moodle/my is because your testing server is not in the root folder.  Not an issue but it will break the links.

**Comment by jamiebillingham** [comment]
Thank you!
