### ISSUE TITLE
New icon/search wastes too much space

### ISSUE THREAD

**Issue by nsheehan** [kennibc/moodle-theme_pioneer#9]
1. Unable to hide these large redundant icons taking up 20% of the page. Please make this an option not a requirement.

**Comment by kennibc** [comment]
OK.  It was part of the plan.  There will be a checkbox next to the frontpage custom text box to turn it on or off.

**Comment by kennibc** [comment]
See the latest on github.  I was in the process of adding the show/hide toggle when you reported it.  It is now here and will be included with the 1.2.6 version on moodle.org.
